import glob
import os

from openpyxl import load_workbook  # type: ignore

"""
This script renames the sheets in Excel files located in a specified directory.
The new sheet names are generated based on the file name.

Functions:
    rename_sheets(file_path):
        Renames the sheets in the Excel file located at file_path.
        The new sheet names are generated by prefixing the original sheet names
        with 'RM_' followed by a part of the file name.

Usage:
    Define the data directory by setting the `data_dir` variable.
    The script processes all Excel files in the data directory that match the pattern 'RM-*.xlsx'.
    For each file, it calls the `rename_sheets` function to rename the sheets.

Example:
"""


def rename_sheets ( file_path ) :
	wb = load_workbook ( file_path )
	rm = file_path.split ( "-" ) [ 1 ]
	
	for sheet in wb.sheetnames :
		new_name = f"RM_{rm}_{sheet}"
		wb [ sheet ].title = new_name
	
	wb.save ( file_path )


# Define the data directory
data_dir = "/path/to/your/data/directory"

# Use this function in your main processing loop
for file in glob.glob ( os.path.join ( data_dir , "RM-*.xlsx" ) ) :
	rename_sheets ( file )
